### ISSUE TITLE
SP Online: Setup new / Existing GW Sharepoint (root and subsite) with Plugin

### ISSUE THREAD

**Issue by mrbrl** [k8-proxy/gp-sharepoint-plugins#11]
Use existing Site
Manually Create
Automate if needed

Use a GW Instance dedicated to this

**Comment by mrbrl** [comment]
@dtollaku let us know what site to use, and if we need to create a new instance, and whereas site creation automation is required.

**Comment by dtollaku** [comment]
https://saaspoc1.sharepoint.com/_forms/default.aspx

**Comment by mrbrl** [comment]
@dtollaku will need credentials as a user and to administrate
