### ISSUE TITLE
Secrets vulnerability to fix

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/gp-sharepoint-plugins#133]
[https://github.com/k8-proxy/gp-sharepoint-plugins/blob/main/Online/glasswall.o365.filehandler/Net5/src/FileHandler/src/Glasswall.O365.FileHandler.App/Glasswall.O365.FileHandler.App.csproj](https://github.com/k8-proxy/gp-sharepoint-plugins/blob/main/Online/glasswall.o365.filehandler/Net5/src/FileHandler/src/Glasswall.O365.FileHandler.App/Glasswall.O365.FileHandler.App.csproj)

**Comment by lohithgn** [comment]
Hi.
I think the vulnerability in question is this line in csproj
```
<UserSecretsId>aspnet-AspNetCoreAadAuth-20EE7806-F48A-49FD-A4BE-7EE1D189EB12</UserSecretsId>
```
This is not a vulnerability. This secret is not an application secret. Rather this is a way to let developers store secrets required by application, on their disk. This is a ASP.NET Core + Visual Studio feature. You can read more about user secrets here: https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=linux

Thanks.

**Comment by PEpetra** [comment]
Reviewed and this can be closed
